export { Header } from "@src/Components/Header/Header";
export { Slider } from "@src/Components/Slider/Slider";
export { TypeWriter } from "@src/Components/TypeWriter/TypeWriter";
export { Footer } from "@src/Components/Footer/Footer";
export { Wrapper } from "@src/Components/Wrapper/Wrapper";
export { BackgroundWord } from "@src/Components/BackgroundWord";
export { LNB } from "@src/Components/LNB/LNB";
export { Layout } from "@src/Components/Layout";
export { WorkDetail } from "@src/Components/WorkDetail";